name: sonarcam-sim-qt5
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pyqt=5.15.*
  - numpy
  - scipy
  - matplotlib
  - pillow
  - xorg-libx11
  - xorg-libxcb
  - xorg-libxext
  - xorg-libxrender
  - xcb-util
  - libxkbcommon
  - pip
  - pip:
      - opencv-python-headless
